# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["VehicleInfoApp.csproj"]
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o /out

# Stage 2: Serve
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
COPY --from=build /out .
EXPOSE 80
ENTRYPOINT ["dotnet", "VehicleInfoApp.dll"]